node {

stage 'Checkout'
git url: 'https://github.com/deshraj5375/deshraj_cicd_practice.git'
def mvnHome = tool 'M3'

stage 'Build'
sh "${mvnHome}/bin/mvn -Dmaven.test.failure.ignore clean package"
#sh "${mvnHome}/bin/mvn -Dmaven.test.failure.ignore clean package"
step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reorts/Test-*.xml'])


}
