node {

stage 'Checkout'
git url: ''
def mvnHome = tool 'M3'

stage 'Build'
sh "${mvnHome}"/bin/mvn -Dmaven.test.failure.ignore clean package"

step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reorts/Test-*.xml'])


}
